services:
  # Serveur Web & PHP
  www:
    build: ./docker
    container_name: tune_php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  # Base de donn√©es MySQL
  db:
    image: mysql:8.0
    container_name: tune_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: test_db
    ports:
      - "3307:3307"

  # PhpMyAdmin (Interface SQL)
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: tune_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db